In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import koreanize_matplotlib

In [4]:
# UTF-8 인코딩으로 파일 불러오기
df1 = pd.read_csv('시도_인구동태건수_및_동태율_출생_사망_혼인_이혼__20240626133710.csv', encoding='utf-8')
df2 = pd.read_csv('시도_시군구별_외국인과의_혼인_20240621182033.csv', encoding='utf-8')

In [5]:
df1.head()

,행정구역별,2013,2013.1,2013.2,2013.3,2013.4,2013.5,2013.6,2013.7,2013.8,...,2023 p).1,2023 p).2,2023 p).3,2023 p).4,2023 p).5,2023 p).6,2023 p).7,2023 p).8,2023 p).9,2023 p).10
0,행정구역별,출생건수 (명),합계출산율,조출생률 (천명당),사망건수 (명),조사망률 (천명당),자연증가건수 (명),자연증가율 (천명당),혼인건수 (건),조혼인율 (천명당),...,합계출산율,조출생률 (천명당),사망건수 (명),조사망률 (천명당),자연증가건수 (명),자연증가율 (천명당),혼인건수 (건),조혼인율 (천명당),이혼건수 (건),조이혼율 (천명당)
1,전국,436455,1.187,8.6,266257,5.3,170198,3.4,322807,6.4,...,0.720,4.5,352700,6.9,-122800,-2.4,193657,3.8,92394,1.8
2,서울특별시,84066,0.968,8.4,42063,4.2,42003,4.2,68819,6.9,...,0.550,4.2,51500,5.5,-12100,-1.3,36324,3.9,12397,1.3
3,부산광역시,25831,1.049,7.4,20096,5.8,5735,1.6,20734,5.9,...,0.660,3.9,26300,8.0,-13400,-4.1,10303,3.1,5452,1.7
4,대구광역시,19340,1.127,7.8,12531,5.0,6809,2.7,13601,5.5,...,0.700,4.0,16600,7.0,-7200,-3.0,8150,3.4,3931,1.7

In [ ]:
columns_to_keep = ['2013']

In [ ]:
columns_to_keep = [col for col in df5.columns if col.isdigit() and len(col) == 4]
df5_cleaned = df5[columns_to_keep]
df5_cleaned.iloc[0] = df5_cleaned.iloc[0].replace('계 (명)', '출생아')

df5_cleaned = df5_cleaned.reset_index(drop=True).iloc[:2]
df5_cleaned = df5_cleaned.drop(columns=['2013', '2014'])
df5_end = df5_cleaned

df5_end = pd.DataFrame([df5_end.iloc[1].values], columns=df5_end.columns)
df5_end.index = ['출생아']

df5_end.head()

In [ ]:
columns_to_keep = ['2016', '2016.9', '2017', '2017.9', '2018', '2018.9', '2019', '2019.9', '2020', '2020.9', '2021', '2021.9', '2022', '2022.9']
df4_cleaned = df4[columns_to_keep]

# 데이터프레임 통합
years = ['2016', '2017', '2018', '2019', '2020', '2021', '2022']
data = {
    '다문화가구원(명)': [df4_cleaned[year][1] for year in years],
    '외국인(결혼이민자)': [df4_cleaned[f"{year}.9"][1] for year in years]
}

# 새로운 데이터프레임 생성 및 전치
df4_end = pd.DataFrame(data, index=years).transpose()

df4_end.head()